version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./app:/app 
    ports:
      - '5000:5000'

  redis:
    image: redis:7.0-alpine
    container_name: redis
    command: redis-server --save 20 1
    ports:
      - '6381:6379'
    volumes:
    - "./redis_db:/data"
